[package]
name = "quafka"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.2"
s2n-quic = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.64"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3.0"
